# Generated by Django 5.2.5 on 2025-10-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3, unique=True)),
                ('compatible_with', models.ManyToManyField(blank=True, to='donations.bloodtype')),
            ],
        ),
    ]
