# Generated by Django 5.2.5 on 2025-10-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_request_options_remove_request_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='request',
            name='hospital',
        ),
    ]
