# Generated by Django 5.2.5 on 2025-10-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_request_options_remove_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='hospital',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
