# Generated by Django 5.2.5 on 2025-11-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_rename_user_request_requester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
