# Generated by Django 5.2.5 on 2025-11-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_request_hospital_alter_appointment_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
