# Generated by Django 5.2.5 on 2025-11-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_request_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
