# Generated by Django 5.2.5 on 2025-11-12 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='has_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'request')},
        ),
    ]
