# Generated by Django 5.2.5 on 2025-11-25 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_remove_notification_message_notification_is_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_reminders_linked', to='donations.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='hospital_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts_linked', to='donations.request'),
        ),
        migrations.AddField(
            model_name='notification',
            name='time_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_notifications_linked', to='donations.request'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='request',
        ),
    ]
