# Generated by Django 5.2.5 on 2025-11-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_alter_notification_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='time_left',
        ),
    ]
