# Generated by Django 5.2.5 on 2025-10-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('hospital', 'Hospital'), ('admin', 'Admin')], default='donor', max_length=20),
        ),
    ]
