# Generated by Django 5.2.5 on 2025-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hospital_remove_customuser_role_and_more'),
        ('donations', '0005_rename_user_request_requester_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
