# Generated by Django 5.2.5 on 2025-11-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_hospital_customuser_role_and_more'),
        ('donations', '0007_request_hospital_alter_appointment_donor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_present_in', to='donations.bloodtype'),
        ),
    ]
