# Generated by Django 5.2.7 on 2025-11-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_blood_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseHospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'accounts_profile',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_hospital_approved',
            field=models.BooleanField(default=False),
        ),
    ]
