# Generated by Django 5.2.7 on 2025-11-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_supabasehospital_customuser_is_hospital_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_user_approved',
            field=models.BooleanField(default=False),
        ),
    ]
