# Generated by Django 5.2.5 on 2025-11-24 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_adminlog'),
        ('donations', '0013_remove_notification_message_notification_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_stock', to='donations.bloodtype')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hospital', 'blood_type')},
            },
        ),
    ]
