# Generated by Django 5.2.7 on 2025-11-25 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_adminlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_user_approved',
        ),
    ]
