# Generated by Django 5.2.5 on 2025-11-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_hospitalbloodstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_user_approved',
        ),
    ]
